# Selenium
selenium_default_implicit_wait_in_seconds = 6
selenium_default_explicit_wait_in_seconds = 10
default_awaiter_interval_in_millis = 10
  
  
  
# Exercise one
first_exercise_url = https://www.888.com/
  
# Exercise one
second_exercise_url = https://www.w3schools.com/html/html_tables.asp